services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: sprintpulse_backend
    depends_on:
      - db
    ports:
      - '3000:3000'

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: sprintpulse_frontend
    ports:
      - '80:80'
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: sprintpulse_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: